### ISSUE TITLE
No exits in RPG or COBOL

### ISSUE THREAD

**Issue by moraghughson** [bpaskin/WASLibertyScriptsAndStuff#1]
Your description of IBM MQ exits suggests that exits can be written in RPG or COBOL. They can't. Application programs that are written in those languages invoke exits that are written in C or 390/ASM. Exits are C, 390/ASM and - only for Java programs - Java.

**Comment by bpaskin** [comment]
Hi Morag, The KC says those languages are supported for exits:
https://www.ibm.com/docs/en/ibm-mq/9.2?topic=reference-channel-exit-calls-data-structures

Did I word something incorrectly?

**Comment by moraghughson** [comment]
RPG and COBOL would appear to be supported for exits on IBM i - your description suggests that COBOL can be used for exits without any restriction. I couldn't write a COBOL exit on z/OS for example. On z/OS I have 390/ASM or C, on most platforms I only have C. I IBM i, I appear to have a few more. Then in Java environments I have Java. So I guess your wording is too all inclusive?

**Comment by bpaskin** [comment]
Ok, I changed the wording and updated the doc.  Thx

**Comment by moraghughson** [comment]
Cheers.
